### ISSUE TITLE
报错 IndexError: list index out of range

### ISSUE THREAD

**Issue by bleudeprusse** [GrokCV/GrokSAR#12]
File "e:\develop_python\python_code\groksar-master\groksar-master\groksar\evaluation\metrics\dota_big2small_metric.py", line 342, in compute_metrics
    x_y_2 = re.findall(r'\d+', x_y[0])
IndexError: list index out of range

**Comment by YimianDai** [comment]
报错信息太少了，没法给出什么靠谱的回答。

看起来是您那边本地数据处理部分的问题。是不是没有切图就调用了切图的配置？看起来是没有找到后缀  __x__y 样子的

**Comment by bleudeprusse** [comment]
上述报错是在用了sar-aircraft-1.0原始数据集，只划分了train、val和test，未切图的情况下发生的。 请问是要先用tools里的img_split.py进行切图吗

**Comment by YimianDai** [comment]
big2small 是切图的配置

**Comment by bleudeprusse** [comment]
你好，我先用img_spilt对图片进行划分python tools\img_split.py E:datasets\SAR-AIRcraft-1.0\JPEGImages 得到split_SAR-AIRcraft-1.0文件，然后执行python tools/train_det.py configs/DenoDet/DenoDet_1x_SAR-AIRcraft-1.0.py 有以下几个疑惑：
1.切图后的split_SAR-AIRcraft-1.0文件结构这样是对的吗？
![1](https://github.com/user-attachments/assets/9834d688-2664-4c04-bac4-4b9d0b08b82f)
![2](https://github.com/user-attachments/assets/d052e3ad-8680-4765-b16c-cfe2f7f4d911)
2.执行python tools/train_det.py configs/DenoDet/DenoDet_1x_SAR-AIRcraft-1.0.py命令后，报错FileNotFoundError: [Errno 2] No such file or directory: 'datasets/split_SAR-AIRcraft-1.0/val/annfiles\\0000002.txt' 在切图之后 后缀不是已经变成0000002__512__0___0、0000002__512__0___312这个格式了吗？有点懵
![3](https://github.com/user-attachments/assets/03921965-744d-4f2f-9f8d-51f255e45fff)
2.修改第75行后
![4](https://github.com/user-attachments/assets/64b05817-cea2-49a5-849a-e0c1bc62e9ce)
能运行，但是训练速度很慢，我设的batch_size=16,num_workers=16,如何才能提高训练速度呢？ config.py文件如下：
[config.txt](https://github.com/user-attachments/files/17309960/config.txt)
刚开始做这方面的研究，所以很多问题不太懂，辛苦大佬解答一下，万分感谢！

**Comment by bleudeprusse** [comment]
补充上一条：
![6](https://github.com/user-attachments/assets/5dcb1474-3a2f-40b8-bcd6-5b1e48f19aab)
![5](https://github.com/user-attachments/assets/8d797936-b4b2-4fa5-9774-db83ed00da7a)
是不是labels的划分的不太对？
![Uploading 7.jpg…]()

**Comment by bleudeprusse** [comment]
你好！我使用了您提供的best_dota_mAP_epoch_10.pth权重文件进行推理

**Comment by bleudeprusse** [comment]
你好！我使用了您给的best_dota_mAP_epoch_10.pth权重文件进行推理，但是预测结果不太好，mAP只有0.375。
![image](https://github.com/user-attachments/assets/97175393-c28b-4140-8c1e-b11be6f0ae60)
不清楚是不是哪里设置有问题。我对比了您的config文件，发现dataset_type = 'sareye.DotaBig2SmallDataset'，而SAR-AIRcraft-1.0.py里写的是dataset_type = 'groksar.DotaBig2SmallDataset'。请问是这里dataset_type的问题吗？
下面是我的log文件：
[20241011_205953.log](https://github.com/user-attachments/files/17343115/20241011_205953.log)

**Comment by travelerwood** [comment]
> 你好！我使用了您给的best_dota_mAP_epoch_10.pth权重文件进行推理，但是预测结果不太好，mAP只有0.375。 ![image](https://private-user-images.githubusercontent.com/76994170/375768075-97175393-c28b-4140-8c1e-b11be6f0ae60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDYxOTQsIm5iZiI6MTcyODcwNTg5NCwicGF0aCI6Ii83Njk5NDE3MC8zNzU3NjgwNzUtOTcxNzUzOTMtYzI4Yi00MTQwLThjMWUtYjExYmU2ZjBhZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA0MDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MWY2MDIwYzQzMDJlMTdkZTA0ODMxNzlkN2FhNzUzMGFkNzIxMmRhNTljOTkxZjhjMTI2YTIwZGFkMWE1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qBEqiBdSTasRb4C0k33GJbgH6EI8jBL-OwzGH4npDYs) 不清楚是不是哪里设置有问题。我对比了您的config文件，发现dataset_type = 'sareye.DotaBig2SmallDataset'，而SAR-AIRcraft-1.0.py里写的是dataset_type = 'groksar.DotaBig2SmallDataset'。请问是这里dataset_type的问题吗？ 下面是我的log文件： [20241011_205953.log](https://github.com/user-attachments/files/17343115/20241011_205953.log)

在 log 文件中，我看到输入的 ground truth 标注文件是小图的标注文件，但是本项目中使用的方法是将大图切成小图进行训练推理、最终将结果合并到大图上的方式，请传入大图的 ground truth 标注文件，谢谢！

**Comment by bleudeprusse** [comment]
非常感谢您的解答，上述问题已经得到解决。但我在尝试用SAR-AIRcraft-1.0数据集进行训练时依旧报错。
![image](https://github.com/user-attachments/assets/10c1a064-5523-47f1-9a6e-3f163adb3744)
日志文件如下：
[20241012_150312.log](https://github.com/user-attachments/files/17349124/20241012_150312.log)

我的猜测是：既然采用切片后的小图进行训练，那么是否应该在train_dataloader中设置tile_mode=True呢？

**Comment by travelerwood** [comment]
> 非常感谢您的解答，上述问题已经得到解决。但我在尝试用SAR-AIRcraft-1.0数据集进行训练时依旧报错。 ![image](https://private-user-images.githubusercontent.com/76994170/375935022-10c1a064-5523-47f1-9a6e-3f163adb3744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTczMTksIm5iZiI6MTcyODcxNzAxOSwicGF0aCI6Ii83Njk5NDE3MC8zNzU5MzUwMjItMTBjMWEwNjQtNTUyMy00N2YxLTlhNmUtM2YxNjNhZGIzNzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3MTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MWJiMGI0NzcxOTIxNGQ3YjliZDI4MzQ0ZWJiZDM0NzM1NDFkZTU2NmVmMGJhNTU0ZjVmNmI1MGQ3ZDBmNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2zASWql1aowZS9VQli-ywDF8g8ZdKMYFaOVTjo7EZug) 日志文件如下： [20241012_150312.log](https://github.com/user-attachments/files/17349124/20241012_150312.log)
> 
> 我的猜测是：既然采用切片后的小图进行训练，那么是否应该在train_dataloader中设置tile_mode=True呢？

报错信息里写的是，未找到图片文件，请检查图片文件路径及后缀名格式，tile_mode 管理的是最后的测试过程，不需要在 train_dataloader 中设置 tile_mode，只需在 validation 和 test 中设置即可。

**Comment by bleudeprusse** [comment]
好的，刚刚发现了文件路径有误，已解决。谢谢！
