### ISSUE TITLE
您好！我在运行MSAR代码时，出现了这种问题，请问怎么解决呢，期待您的回复

### ISSUE THREAD

**Issue by ayuanyuany** [GrokCV/GrokSAR#13]
![屏幕截图 2024-10-12 161750](https://github.com/user-attachments/assets/a927c00c-00c3-4969-b448-7d92b4412dca)

**Comment by YimianDai** [comment]
字面意义，就是图片大小和模型预设的不匹配；
和 #3 重复

**Comment by ayuanyuany** [comment]
谢谢您的耐心解答，目前问题已经解决。



---- 回复的原邮件 ----
| 发件人 | Yimian ***@***.***> |
| 日期 | 2024年10月13日 22:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [GrokCV/GrokSAR] 您好！我在运行MSAR代码时，出现了这种问题，请问怎么解决呢，期待您的回复 (Issue #13) |

Closed #13 as completed.

**Comment by Yin-Xiangjie** [comment]
> 谢谢您的耐心解答，目前问题已经解决。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Yimian ***@***.***> | | 日期 | 2024年10月13日 22:27 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [GrokCV/GrokSAR] 您好！我在运行MSAR代码时，出现了这种问题，请问怎么解决呢，期待您的回复 (Issue #13) | Closed #13 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你好，请问您的代码已经完全跑通了吗？

**Comment by ayuanyuany** [comment]
谢谢老师，问题已经解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月19日 11:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [GrokCV/GrokSAR] 您好！我在运行MSAR代码时，出现了这种问题，请问怎么解决呢，期待您的回复 (Issue #13) |

谢谢您的耐心解答，目前问题已经解决。
…
---- 回复的原邮件 ---- | 发件人 | Yimian @.> | | 日期 | 2024年10月13日 22:27 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [GrokCV/GrokSAR] 您好！我在运行MSAR代码时，出现了这种问题，请问怎么解决呢，期待您的回复 (Issue #13) | Closed #13 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

你好，请问您的代码已经完全跑通了吗？
