### ISSUE TITLE
训练结果无法达到预期

### ISSUE THREAD

**Issue by bleudeprusse** [GrokCV/GrokSAR#14]
作者您好，我在用SAR-AIRcraft-1.0数据集训练模型时，在验证集上的最佳精度为0.858，低于您日志中的0.861，而在测试集上的精度为0.663，低于您的0.686。
我的gpu是3070，batch_size=8,num_worker=4,base_lr=1/4，epoch=12 。请问我该进行哪些修改 以提升精度呢？
我的训练日志文件：
[20241013_044552.log](https://github.com/user-attachments/files/17358940/20241013_044552.log)
@travelerwood @YimianDai

**Comment by travelerwood** [comment]
请先尝试使用仓库中提供的 checkpoints 模型文件，推理验证数据集配置是否一致。此外，base_lr 和优化器设置保持与本仓库一致即可。

**Comment by bleudeprusse** [comment]
我在使用了仓库提供的checkpoints 模型文件进行推理后，得到mAP为0.686，和论文中的精度保持一致。因此数据集设置没有问题。
并且我此前也尝试过 在不修改base_lr，仅设置batch_size=8,num_worker=4的情况下，在验证集上的最高精度依旧只有0.854，测试集上的精度为0.662。由于gpu显存太小，batch_size设不了32。所以是batch_size减小所导致的吗？

**Comment by travelerwood** [comment]
在 batch_size 较低的情况下，可以尝试增大训练轮数 epoch 并降低学习率 base_lr，理论上应该可以达到同样的效果。
