### ISSUE TITLE
请问这个错误应该怎么解决呢

### ISSUE THREAD

**Issue by ayuanyuany** [GrokCV/GrokSAR#15]
![屏幕截图 2024-10-20 164055](https://github.com/user-attachments/assets/2b1a5df3-0b6c-4649-b197-3b2b1acbd679)

**Comment by YimianDai** [comment]
目前所提供的信息太少，不好分析。先 check 您那边的路径是否匹配

**Comment by travelerwood** [comment]
> ![屏幕截图 2024-10-20 164055](https://private-user-images.githubusercontent.com/184797145/378168508-2b1a5df3-0b6c-4649-b197-3b2b1acbd679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTUyMjcsIm5iZiI6MTcyOTU5NDkyNywicGF0aCI6Ii8xODQ3OTcxNDUvMzc4MTY4NTA4LTJiMWE1ZGYzLTBiNmMtNDY0OS1iMTk3LTNiMmIxYWNiZDY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMTAyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjg5ZjAyZWQxOGNmMDFkYTkzODk3MmFhMWViMGRlNTY3ZjhmYmQ5OGI3YjVjNzg3NjI3N2UxMDM2OTA3M2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DEkOnvkBKn4M9Viyc_Ko8LqyB5fDJn1OhnlmXgFfM_0)

请按照本仓库中的配置文件示例，使用 img_suffix 规定图片文件后缀名，如下所示：
```python
val_dataloader = dict(
    batch_size=32,
    num_workers=8,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        metainfo=METAINFO,
        data_prefix=dict(img_path='datasets/split_SAR-AIRcraft-1.0/val/images'),
        img_suffix='jpg',
        ann_file='datasets/SAR-AIRcraft-1.0/dota/val/labels/',
        test_mode=True,
        tile_mode=True,
        pipeline=val_pipeline,
    ))
``` 
此外，请检查文件名或文件路径是否有误。
