### ISSUE TITLE
SARShip-1.0检测结果为0

### ISSUE THREAD

**Issue by 1whiteuncle** [GrokCV/GrokSAR#16]
![image](https://github.com/user-attachments/assets/5c6273ae-8b7e-4fe5-8f1b-97cca90f915a)
![image](https://github.com/user-attachments/assets/42251940-cc04-42a0-b196-80e034c0dc15)
![image](https://github.com/user-attachments/assets/c6aae9d3-7cd2-47e2-bf42-3411995f6221)

能够正常训练和检测，可是检测结果为0，不知道哪里出现了问题，请求帮助。

**Comment by 1whiteuncle** [comment]
问题出现场景是：用了作者的代码，将数据集分为训练和测试，使用了作者提供的权重文件best_dota_mAP_epoch_30.pth作为预训练权重文件。
![image](https://github.com/user-attachments/assets/68be31ff-9c9c-4833-a7c9-03dd020d5c5b)

**Comment by travelerwood** [comment]
现有信息无法获知具体原因，请提供所使用的配置文件和日志文件等信息，用于进一步分析。
@1whiteuncle

**Comment by 1whiteuncle** [comment]
[20241029_115659.log](https://github.com/user-attachments/files/17551411/20241029_115659.log)
![image](https://github.com/user-attachments/assets/9075d787-ad33-4bef-9bdc-eba520ae7c9e)
![image](https://github.com/user-attachments/assets/a2e043dd-0ead-42e4-9fd8-95ca41b19a27)

日志文件如上；数据集如上；这个是作者提供的配置文件，只改动了权重文件的输入；请求帮助。

**Comment by 1whiteuncle** [comment]
我把图片切分之后，进行训练，结果依然为0。不知道为题出在哪？请求帮助
![image](https://github.com/user-attachments/assets/aeea5929-b7b3-4ba2-b2f9-dd172ff41c3e)
![image](https://github.com/user-attachments/assets/aa649c39-1033-4a4f-a35f-efd02741b514)
[20241030_154335.log](https://github.com/user-attachments/files/17568017/20241030_154335.log)
把这部分进行了简单改动，输出的ID啥的是正确的
![image](https://github.com/user-attachments/assets/2c0de1c3-c86c-4944-8dd8-d0c6c8fa6d7b)

**Comment by travelerwood** [comment]
是否使用了本仓库 `GrokSAR/tools/split_configs` 中的 json 脚本作为切分的配置文件？使用命令为
```shell
python tools/img_split.py --base-json tools/split_configs/AIR-SARShip-1.0_train.json
```
