### ISSUE TITLE
根据作者提示，已对图像切分，训练结果为0，请求回复

### ISSUE THREAD

**Issue by 1whiteuncle** [GrokCV/GrokSAR#17]
我把图片切分之后，进行训练，结果依然为0。不知道为题出在哪？请求帮助
![image](https://github.com/user-attachments/assets/aeea5929-b7b3-4ba2-b2f9-dd172ff41c3e)
![image](https://github.com/user-attachments/assets/aa649c39-1033-4a4f-a35f-efd02741b514)
[20241030_154335.log](https://github.com/user-attachments/files/17568017/20241030_154335.log)
把这部分进行了简单改动，输出的ID啥的是正确的
![image](https://github.com/user-attachments/assets/2c0de1c3-c86c-4944-8dd8-d0c6c8fa6d7b)
![image](https://github.com/user-attachments/assets/4b901586-7b41-4fcc-b191-069aabfc48c9)

**Comment by YimianDai** [comment]
DenoDet 是构建在 MMRotate、MMDetection 框架之上的，您的问题是不熟悉 MMRotate 框架、DOTA 数据集等导致的，和 DenoDet 代码无关，，建议您先熟悉下 MMRotate、MMDetection。
