### ISSUE TITLE
你好，请问SAR-AIRcraft-1.0数据集的划分以及路径是如何放置的

### ISSUE THREAD

**Issue by Yin-Xiangjie** [GrokCV/GrokSAR#18]
你好我在运行代码时貌似遇到了文件路径和文件名称获取的问题，一个是SAR-AIRcraft-1.0数据集的划分以及路径是如何放置的。另一个是dota_big2small_metric的作用是什么？

**Comment by travelerwood** [comment]
您好，感谢您关注并使用本仓库的代码。关于您的问题，我们的回答如下：
1. SAR-AIRcraft-1.0 数据集在发布时已经划分好了训练集、验证集和测试集，为保证公平，本仓库中使用的是原数据集的划分格式。
2. 关于路径的放置，正如我们在配置文件`configs/_base_/datasets/SAR-AIRcraft-1.0.py`中写到的那样，我们将所有的数据集都统一放置在 `datasets` 目录下。特别对于 SAR-AIRcraft-1.0 数据集，我们使用了 `tools/img_split.py` 脚本来生成切分成 `512 * 512` 大小的子图集，仍然放在 `datasets` 文件夹下。最简单的使用方式是，下载原始数据集后，将图片文件和本仓库中已经转换好的 `DOTA` 格式标注文件放置在同一文件夹下，并使用本仓库提供的子图切分脚本和配置文件进行图片切分，使用命令如下：
```shell
python tools/img_split.py --base-json tools/split_configs/SAR-AIRcraft-1.0_train.json
python tools/img_split.py --base-json tools/split_configs/SAR-AIRcraft-1.0_val.json
python tools/img_split.py --base-json tools/split_configs/SAR-AIRcraft-1.0_test.json
```
3. 关于 `dota_big2small_metric.py` 脚本，本仓库中，为提高训练效率并提升 SAR 图像目标检测的性能。使用的方式是将高分辨率的 SAR 图像切分成 `512 * 512` 的小图进行训练推理，同时为保证公平性，再将小图的检测结果合并到大图上，并与大图的原始标注进行对比的方式。`dota_big2small_metric.py` 脚本是用于实现这一功能的检测结果展示脚本。
