### ISSUE TITLE
请教包冲突怎么解决

### ISSUE THREAD

**Issue by lwz021** [GrokCV/GrokSAR#20]
博主您好，在配置环境的时候，按您给出的安装步骤，在conda的命令行输入：
mim install mmengine "mmcv>=2.0.0" "mmdet>=3.0.0" "mmsegmentation>=1.0.0" "mmrotate>=1.0.0rc1" mmyolo
后，出现包冲突的提示，该怎么解决呢？是因为不能用windows操作系统吗？还是因为没有指定mmyyolo的版本呢？
<img width="861" alt="报错" src="https://github.com/user-attachments/assets/0924ba71-0cb0-4c1c-93de-1b4f4692719c" />

**Comment by travelerwood** [comment]
感谢您的关注与反馈！关于您的问题，我们的回答如下：
经过测试，在上一次 `python` 的版本更新后，原有的安装指令中 `MMDet` 与 `python` 版本冲突而失效，我们已经更新了最新经过测试不会报错的安装指令。更新后的安装指令如下：
```shell
conda create --name groksar python=3.8
source activate groksar
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.8 -c pytorch -c nvidia
# openmmlab codebases
pip install -U openmim dadaptation cmake lit --no-input
mim install mmengine "mmcv>=2.0.0rc4, <2.1.0" "mmdet>=3.0.0rc5, < 3.1.0" "mmsegmentation>=1.0.0" "mmrotate>=1.0.0rc1" mmyolo mmpretrain
# heatmap generation dependencies
pip install grad-cam==1.4.0
# other dependencies
pip install ninja --no-input
pip install scikit-learn
pip install psutil
git clone git@github.com:GrokCV/groksar.git
cd groksar
python setup.py develop
```
