### ISSUE TITLE
请教grokSAR安装失败的问题

### ISSUE THREAD

**Issue by lwz021** [GrokCV/GrokSAR#21]
博主您好，在安装grokSAR这一步，命令行执行python setup.py develop的时候报错很多警告，请教一下是什么原因呢？怎么解决呀？
<img width="850" alt="安装grokSAR报错" src="https://github.com/user-attachments/assets/cfcd64e8-a1ce-4dd3-beb9-6646c42229c2" />

**Comment by travelerwood** [comment]
感谢您的使用与关注！关于您的问题，我们的回答如下：
由于本仓库将长期更新，所以在 setup.py 文件中，我们预留了大量后续更新脚本时可能会上传的文件夹路径。这些 warning 代表预留的文件夹中还没有增加脚本，但并不会对代码的安装和使用造成任何影响，谢谢！
