### ISSUE TITLE
Questions about AP'12 Metric and Image Splitting in SAR-Aircraft-1.0 Dataset

### ISSUE THREAD

**Issue by updateforever** [GrokCV/GrokSAR#5]
First of all, thank you for your valuable work and for sharing the codebase. I have a couple of questions regarding the paper and the dataset used:
1.AP'12 Metric Calculation:

In the paper, you mention the use of the AP'12 metric. From my understanding, VOC 2007 does not define an AP'12 metric. Could you please provide more details on how this metric is calculated? Specifically, what are the 12 points used for the AP'12 calculation?

2.Image Splitting in SAR-Aircraft-v1 Dataset:

The paper mentions that the SAR-Aircraft-v1 dataset involves splitting images. Could you clarify the reasoning behind the image splitting operation?
Additionally, could you point me to the location of the code in the repository where this image splitting is performed?

Thank you for your assistance!

**Comment by travelerwood** [comment]
> First of all, thank you for your valuable work and for sharing the codebase. I have a couple of questions regarding the paper and the dataset used: 1.AP'12 Metric Calculation:
> 
> In the paper, you mention the use of the AP'12 metric. From my understanding, VOC 2007 does not define an AP'12 metric. Could you please provide more details on how this metric is calculated? Specifically, what are the 12 points used for the AP'12 calculation?
> 
> 2.Image Splitting in SAR-Aircraft-v1 Dataset:
> 
> The paper mentions that the SAR-Aircraft-v1 dataset involves splitting images. Could you clarify the reasoning behind the image splitting operation? Additionally, could you point me to the location of the code in the repository where this image splitting is performed?
> 
> Thank you for your assistance!

Thank you for feedback! Here are the response to the questions you raised:
#### Question 1:
The AP'12 standard refers to the AP evaluation metric used in the VOC 2012 dataset. Unlike the VOC 2007 dataset, which uses the average of 11 points on the Precision-Recall (P-R) curve, the VOC 2012 dataset calculates the area under the lower part of the P-R curve, or in other words, it averages all points on the P-R curve. To use the AP'12 standard, you need to change the 11points setting to area in the dataset's configuration. Taks SAR-AIRcraft-1.0 dataset as example, the specific code is as follows:

> [GrokSAR/configs/_base_/datasets/SAR-AIRcraft-1.0.py](https://github.com/GrokCV/GrokSAR/blob/master/configs/_base_/datasets/SAR-AIRcraft-1.0.py)

Lines 82
```python
val_evaluator = dict(type='groksar.DotaBig2SmallMetric', metric='mAP', eval_mode='11points')
```

Should be rewriten as:
```python
val_evaluator = dict(type='groksar.DotaBig2SmallMetric', metric='mAP', eval_mode='area')
```

For convenience, we will differentiate between the VOC 07 and VOC 12 versions in the dataset configuration in the next version update.
#### Question 2:
There are at least two reasons for cropping images in the SAR-AIRcraft-1.0 dataset: 
1. The SAR-AIRcraft-1.0 dataset does not have a fixed resolution, but CNN networks typically require images to be resized to a fixed size. To ensure that the target does not shift or distort and to make the network structure more general, we crop all images to a size of 512 x 512. 
2. Reducing the resolution helps lower computational complexity and ease the burden on devices. Moreover, our detection results are compared with the annotations on the original large images, ensuring the fairness of data usage.

The code for dataset splitting can be found at the following path:
> [GrokSAR/tools/img_split.py](https://github.com/GrokCV/GrokSAR/blob/master/tools/img_split.py)

And you can use it with the following code:
```bash
python tools/img_split.py --base-json tools/split_configs/SAR-AIRcraft-1.0_train.json
python tools/img_split.py --base-json tools/split_configs/SAR-AIRcraft-1.0_val.json
python tools/img_split.py --base-json tools/split_configs/SAR-AIRcraft-1.0_test.json
```

**Comment by JingofGao** [comment]
I have another question. What is AP'07 metric and how to use this metric to evaluate the model by modifying the "SAR-AIRcraft-1.0.py" file?

**Comment by travelerwood** [comment]
> I have another question. What is AP'07 metric and how to use this metric to evaluate the model by modifying the "SAR-AIRcraft-1.0.py" file?

Thank you for using and paying attention to this repository. As mentioned in the previous comments:
AP'07 and AP'12 are both metrics for measuring detection quality, and the configuration setting for AP'07 metric is:
```python
val_evaluator = dict(type='groksar.DotaBig2SmallMetric', metric='mAP', eval_mode='11points')
```
And the configuration setting for AP'12 metric is:
```python
val_evaluator = dict(type='groksar.DotaBig2SmallMetric', metric='mAP', eval_mode='area')
```
