### ISSUE TITLE
SAR image inference

### ISSUE THREAD

**Issue by tbxmh** [GrokCV/GrokSAR#6]
May I ask how to use the weights you provide to test my own SAR images? Can you tell me the specific operating steps?

**Comment by travelerwood** [comment]
> May I ask how to use the weights you provide to test my own SAR images? Can you tell me the specific operating steps?

Thank you for feedback! If you need to conduct experiments on other datasets, you will need to modify several parts of the configuration files, here are the steps you may need to complete:

1. Modify the dataset configuration file based on your dataset such as class names, path, dataset format.
2. Modify the model configuration file, calculate the mean and standard deviation of the pixels according to your dataset, and adjust the `class_numbers` in the model based on your dataset.
3. Use the modified configuration files during training and inference.
