### ISSUE TITLE
Pretrained Checkpoint on OneDrive

### ISSUE THREAD

**Issue by timchang27** [GrokCV/GrokSAR#7]
Hi, could you release the OneDrive link to your pretrained model checkpoints? The current links on readme are empty and I am not able to access the Baidu network drive links.

Thank you!

**Comment by YimianDai** [comment]
Hi there,

I've updated the ReadMe, and the OneDrive links for the pretrained model checkpoints are now available. Please note that the README for this repository is still under construction, and I apologize for any inconvenience this may have caused.

Thank you for your patience and support for this project.
