### ISSUE TITLE
poor performance in my own model

### ISSUE THREAD

**Issue by JarvisKevin** [GrokCV/GrokSAR#9]
I copied DenoDet.py into the mmrotate neck folder and used it in my detection model. The training loss before using FrequencySpatialFPN was around 0.2, and it dropped to 0.09 after incorporating FrequencySpatialFPN. However, the inference results with FrequencySpatialFPN are very poor. Is there a problem with my implementation?

**Comment by YimianDai** [comment]
Have Discussed on WeChat, Closed.
